###Get All Users
GET http://localhost:9007/users
Accept: application/json

### Get user by id
GET http://localhost:9007/users/12
Accept: application/json

###Create User
POST http://localhost:9007/users
Content-Type: application/json

{
  "id": 15,
  "name": "New User",
  "email": "new@gmail.com",
  "contact": "new contact",
  "address": "jaipur"
}

###Update user
PUT http://localhost:9007/users/12
Content-Type: application/json

{
  "name": "Updated User",
  "email": "update@gmail.com",
  "contact": "update contact",
  "address": "updated city"
}